COLUMNS:
  age: float64  
  gender: object 
  region_category: object
  membership_category: object
  joined_through_referral: object
  preferred_offer_types: object
  internet_option: object
  Recency: float64  
  avg_time_spent: float64  
  Monetary: float64  
  Frequency: float64  
  points_in_wallet: float64  
  used_special_discount: object
  offer_application_preference: object
  past_complaint: object
  complaint_status: object
  feedback: object
  churn_risk_score: int64
  medium_of_operation: object
  tenure_months: int64  
  visit_hour: int64  
  Login-Spend Ratio: float64  
  Login-Transaction Ratio: float64  

TARGET_COLUMN:
  name: churn_risk_score
